name: Deploy Terminal Config
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: inventory configuration
      run: |
        cat <<EOF > ansible/hosts.ini
        ${{ secrets.ANSIBLE_INVENTORY }}
        EOF

    - name: syntax verif
      run: |
        ansible-playbook -i ansible/hosts.ini ansible/setup_term.yml --syntax-check

    #- name: Dry-run Bootstrap
    #  run: |
    #    ansible-playbook -i ansible/hosts.ini ansible/start.yml --check \
    #    --extra-vars "ansible_become_pass=${{ secrets.ANSIBLE_SUDO_PASS }}"
    #
    #- name: dry-run
    #  env:
    #    SUDO_PASS: ${{ secrets.ANSIBLE_SUDO_PASS }}
    #  run: |
    #    ansible-playbook -i ansible/hosts.ini ansible/setup_term.yml \
    #    --extra-vars "ansible_become_pass=$SUDO_PASS" \
    #    --check

    - name: Run Bootstrap (Root)
      env:
        SUDO_PASS: ${{ secrets.ANSIBLE_SUDO_PASS }}
      run: |
        ansible-playbook -i ansible/hosts.ini ansible/start.yml \
        --extra-vars "ansible_become_pass=$SUDO_PASS"

    - name: execute ansible-playbook
      env:
        SUDO_PASS: ${{ secrets.ANSIBLE_SUDO_PASS }}
      run: |
        ansible-playbook -i ansible/hosts.ini ansible/setup_term.yml \
        --extra-vars "ansible_become_pass=$SUDO_PASS"
